---
- name: Deploy Docker Container on EC2
  hosts: ec2_instances  # Should match the inventory group name
  become: yes
  vars:
    github_repo: "https://github.com/Riyazrizz/cicd.git"
    docker_image_name: "myapp_image"
    docker_container_name: "myapp_container"
    repo_dest: "/home/ubuntu/myapp"
    dockerfile_dir: "/home/ubuntu/myapp/Task 2"  # Correct Dockerfile path

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone the GitHub repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ repo_dest }}"
        version: master
        force: yes

    - name: Build Docker image from Dockerfile
      docker_image:
        path: "{{ dockerfile_dir }}"
        name: "{{ docker_image_name }}"
        tag: latest

    - name: Run the Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "80:80"
