name: Deploy Docker on EC2 with Ansible

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for this job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ansible
      - name: Set up Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          ansible_version: 'latest'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install boto3 ansible

      # Step 4: Add SSH private key for EC2
      - name: Add SSH private key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 5: Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "54.194.37.244" --private-key P.pem --user ubuntu --extra-vars "github_repo=https://github.com/Riyazrizz/cicd.git docker_image_name=myapp_image docker_container_name=myapp_container" install_docker.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"  # Disable host key checking for EC2 instance
