name: Deploy Docker on EC2 with Ansible

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for this job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # # Step 2: Set up Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install boto3 ansible

      # Step 4: Add SSH private key for EC2
      - name: Add SSH private key
        run: |
          ls
          pwd
          cd 'Task 2'
          ls
          chmod 600 P.pem
          echo "[ec2_instances]" > inventory.ini
          ansible-playbook -i inventory.ini install_docker.yml -vvv --ssh-extra-args="-o StrictHostKeyChecking=no"
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  # Secret containing the private key
          ANSIBLE_HOST_KEY_CHECKING: "false"  # Disable host key checking for EC2 instance
          
