name: Deploy Docker on EC2 with Ansible

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for this job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ansible
      - name: Set up Ansible
        run: sudo apt install ansible

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install boto3 ansible


      # Step 5: Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |          
          cd 'Task 2'
          ls
          ansible-playbook -i "54.194.37.244" --private-key P.pem install_docker.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"  # Disable host key checking for EC2 instance
